name: Mod Update
description: Suggest a mod to be updated in Create Survive & Explore.
title: "[MOD] "
labels: mod, update

body:
  - type: markdown
    attributes:
      value: |
        Before suggesting a mod update, [please search](https://github.com/kkempfer/Create-Survive-Explore/issues) to make sure it has not already been suggested.

  - type: textarea
    id: why
    attributes:
      label: Why should we update this mod in this modpack?
      description: Provide some explanations, please be concise and clear.
    validations:
        required: true

  - type: textarea
    id: additional_details
    attributes:
      label: Additional details
      description: Is there anything else you want to add?

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirm
      options:
        - label: This is not a new mod addition or mod replacement request. For that purpose, I should use the mod request form.
          required: true
        - label: This is not a mod removal request. For that purpose, I should use the mod removal form.
          required: true
