enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
naturalist = true
corndelight = true
seasonsextras = true
farmersdelight = true
cratedelight = true
supplementaries = true
chipped = true
create = true
oceansdelight = true
ecologics = true
copycats = true
minecraft = true
animal_feeding_trough = true
comforts = true
yigd = true
nethersdelight = true
create_jetpack = true
createdeco = true
createfoundry = true
create_enchantment_industry = true
railways = true
oxirods = true
createaddition = true
bellsandwhistles = true
createchunkloading = true
sliceanddice = true
milk = true
decorative_blocks = true
display_case = true
dehydration = true
ftbquests = true
snowrealmagic = true
extendedgears = true
expandeddelight = true
delightfulcreators = true
creategoggles = true
