placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = true
snowAccumulationMaxLayers = 9
thinnerBoundingBox = true
snowMakingIce = false
snowOnIce = false
snowNeverMelt = false
snowMeltsInWarmBiomes = false
snowNaturalMelt = true
snowReduceFallDamage = true
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = false
sneakSnowball = true
mobSpawningMaxLayers = 16
